### ISSUE TITLE
Material-Theme for Documentation

### ISSUE THREAD

**Issue by vinayhegde1990** [vinayhegde1990/devops-notes#3]
Evaluate **[Material theme](https://squidfunk.github.io/mkdocs-material)** availability for ReadTheDocs

**Comment by vinayhegde1990** [comment]
- [ ] First, test it on staging Home PC environment.
- [ ] Then deploy to production, check via PC & Mobile.
- [ ] Rollback to previous theme on improper rendering.

**Comment by vinayhegde1990** [comment]
- [x] Test it on staging environment.
- [x] Deploy to production, check via PC & Mobile.
- [x] Rollback to previous theme on improper rendering, done due to **[Issue](https://github.com/squidfunk/mkdocs-material/issues/43)**

**Comment by arich-net** [comment]
I am not able to use material theme on readthedocs still. Any suggestion?

**Comment by vinayhegde1990** [comment]
> I am not able to use material theme on readthedocs still. Any suggestion?

@arich-net the above comments should help
